#crear un var
saludo= "hola mundo!!!"
print(saludo)


#suma de numeros
num1 = 10
num2 = 20
suma = num1 + num2
print(suma)

#suma de palabras
palabra1 = "hola"
palabra2 = "mundo"
suma_palabra = palabra1 +"" + palabra2
print(suma_palabra)

#resta de numeros
resta1 = 10
resta2 = -4
resta = num1 - num2
print(resta)

#multiplicacion de numeros
mult1 = 3
mult2 = 5
multiplicacion = mult1 * mult2
print(multiplicacion)

#division de numeros
divi1 = 10
divi2 = 2
division = divi1 / divi2
print(division)